#!/usr/bin/env bash
#
# This script is for quickly generate helpful info
#

cd "$(dirname "$0")";export base="$(pwd)"
output_file=diagnose.result;rm $output_file
export LANG=C;export LC_ALL=C
case $(whoami) in
  root)echo -e "\e[31m[$0]: 此脚本不应使用 sudo 或以 root 身份执行。正在中止...\e[0m";exit 1;;
esac


x() { ii_exec "$@" 2>&1 | tee -a $output_file ; }
e() { ii_box "$@" | tee -a $output_file ; }
ii_box() {
  length=$(echo "$1" | wc -L);total_width=$((length + 2))
  #line=$(printf "═%.0s" $(seq 1 $total_width))
  #border_up="╔${line}╗";border_down="╚${line}╝"
  #border_vertical="║"
  line=$(printf "=%.0s" $(seq 1 $total_width))
  border_up="/${line}\\";border_down="\\${line}/"
  border_vertical="|"
  echo -e "\n$border_up"
  echo "$border_vertical $1 $border_vertical"
  echo "$border_down"
}
ii_exec() {
  printf "\n[===diagnose===] $*\n"
  "$@"
  err=$?;if [ ! $err -eq 0 ];then echo "[---EXIT $err---]";else echo "[---SUCCESS---]";fi
}
ii_check_distro() {
  lsb_release -a || cat /etc/os-release || cat /etc/lsb-release
}
ii_check_venv() {
  source $(eval echo $ILLOGICAL_IMPULSE_VIRTUAL_ENV)/bin/activate
  which python
  deactivate
}

e "检查 git 仓库信息"
x git remote get-url origin
x git rev-parse HEAD

e "检查发行版"
x ii_check_distro 

e "检查变量"
x declare -p XDG_CACHE_HOME # ~/.cache
x declare -p XDG_CONFIG_HOME # ~/.config
x declare -p XDG_DATA_HOME # ~/.local/share
x declare -p XDG_STATE_HOME # ~/.local/state
x declare -p ILLOGICAL_IMPULSE_VIRTUAL_ENV # $XDG_STATE_HOME/quickshell/.venv

e "检查目录/文件"
x ls -l ~/.local/state/quickshell/.venv
#x cat ~/.config/ags/

#e "Checking command existence"
#commands=(yay pacman zypper apt dnf yum)
commands+=(ags agsv1)
#commands+=(Hyprland hypr{ctl,idle,lock,picker})
#commands+=(uv)
#for i in "${commands[@]}";do x command -v $i;done

e "检查版本"
x Hyprland --version

e "已完成。输出已保存为 \"$output_file\"。"
if ! command -v curl 2>&1 >>/dev/null ;then echo "未找到 \"curl\"，无法上传到 pastebin。";exit;fi
echo "(可选) 您同意将文件 \"$output_file\" 上传到在线 pastebin (https://0x0.st) 吗？"
echo "注意："
echo "1. 这是一个公共服务，日志文件将在 15 天后过期。"
echo "2. 在同意上传之前，您应该先查看 \"$output_file\" 的内容。"
echo "3. 仅在必要时同意，通常是在您创建 issue 并且无法在那里上传 \"diagnose.result\" 文件或直接复制粘贴输出时。"
read -p "y=是, n=否 (默认) ====> " p
case $p in
  [yY]) echo "好的，正在上传..."
        curl -F'file=@diagnose.result' -Fexpires=360 https://0x0.st && \
          echo "上传完成。寻求帮助时请附上以上 URL。"
        ;;
  *) echo "已中止上传。";;
esac
