// List of rows
const elements = [
    [
        { name: '氢', symbol: 'H', number: 1, weight: 1.01, type: 'nonmetal' },
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
        { name: '氦', symbol: 'He', number: 2, weight: 4.00, type: 'noblegas' },
    ],
    [
        { name: '锂', symbol: 'Li', number: 3, weight: 6.94, type: 'metal' },
        { name: '铍', symbol: 'Be', number: 4, weight: 9.01, type: 'metal' },
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
        { name: '硼', symbol: 'B', number: 5, weight: 10.81, type: 'nonmetal' },
        { name: '碳', symbol: 'C', number: 6, weight: 12.01, type: 'nonmetal' },
        { name: '氮', symbol: 'N', number: 7, weight: 14.01, type: 'nonmetal' },
        { name: '氧', symbol: 'O', number: 8, weight: 16, type: 'nonmetal' },
        { name: '氟', symbol: 'F', number: 9, weight: 19, type: 'nonmetal' },
        { name: '氖', symbol: 'Ne', number: 10, weight: 20.18, type: 'noblegas' },


    ],
    [
        { name: '钠', symbol: 'Na', number: 11, weight: 22.99, type: 'metal' },
        { name: '镁', symbol: 'Mg', number: 12, weight: 24.31, type: 'metal' },
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
        { name: '铝', symbol: 'Al', number: 13, weight: 26.98, type: 'metal' },
        { name: '硅', symbol: 'Si', number: 14, weight: 28.09, type: 'nonmetal' },
        { name: '磷', symbol: 'P', number: 15, weight: 30.97, type: 'nonmetal' },
        { name: '硫', symbol: 'S', number: 16, weight: 32.07, type: 'nonmetal' },
        { name: '氯', symbol: 'Cl', number: 17, weight: 35.45, type: 'nonmetal' },
        { name: '氩', symbol: 'Ar', number: 18, weight: 39.95, type: 'noblegas' },
    ],
    [
        { name: '钾', symbol: 'K', number: 19, weight: 39.098, type: 'metal' },
        { name: '钙', symbol: 'Ca', number: 20, weight: 40.078, type: 'metal' },
        { name: '钪', symbol: 'Sc', number: 21, weight: 44.956, type: 'metal' },
        { name: '钛', symbol: 'Ti', number: 22, weight: 47.87, type: 'metal' },
        { name: '钒', symbol: 'V', number: 23, weight: 50.94, type: 'metal' },
        { name: '铬', symbol: 'Cr', number: 24, weight: 52, type: 'metal'/*, icon: 'chromium-browser'*/ },
        { name: '锰', symbol: 'Mn', number: 25, weight: 54.94, type: 'metal' },
        { name: '铁', symbol: 'Fe', number: 26, weight: 55.85, type: 'metal' },
        { name: '钴', symbol: 'Co', number: 27, weight: 58.93, type: 'metal' },
        { name: '镍', symbol: 'Ni', number: 28, weight: 58.69, type: 'metal' },
        { name: '铜', symbol: 'Cu', number: 29, weight: 63.55, type: 'metal' },
        { name: '锌', symbol: 'Zn', number: 30, weight: 65.38, type: 'metal' },
        { name: '镓', symbol: 'Ga', number: 31, weight: 69.72, type: 'metal' },
        { name: '锗', symbol: 'Ge', number: 32, weight: 72.63, type: 'metal' },
        { name: '砷', symbol: 'As', number: 33, weight: 74.92, type: 'nonmetal' },
        { name: '硒', symbol: 'Se', number: 34, weight: 78.96, type: 'nonmetal' },
        { name: '溴', symbol: 'Br', number: 35, weight: 79.904, type: 'nonmetal' },
        { name: '氪', symbol: 'Kr', number: 36, weight: 83.8, type: 'noblegas' },
    ],
    [
        { name: '铷', symbol: 'Rb', number: 37, weight: 85.47, type: 'metal' },
        { name: '锶', symbol: 'Sr', number: 38, weight: 87.62, type: 'metal' },
        { name: '钇', symbol: 'Y', number: 39, weight: 88.91, type: 'metal' },
        { name: '锆', symbol: 'Zr', number: 40, weight: 91.22, type: 'metal' },
        { name: '铌', symbol: 'Nb', number: 41, weight: 92.91, type: 'metal' },
        { name: '钼', symbol: 'Mo', number: 42, weight: 95.94, type: 'metal' },
        { name: '锝', symbol: 'Tc', number: 43, weight: 98, type: 'metal' },
        { name: '钌', symbol: 'Ru', number: 44, weight: 101.07, type: 'metal' },
        { name: '铑', symbol: 'Rh', number: 45, weight: 102.91, type: 'metal' },
        { name: '钯', symbol: 'Pd', number: 46, weight: 106.42, type: 'metal' },
        { name: '银', symbol: 'Ag', number: 47, weight: 107.87, type: 'metal' },
        { name: '镉', symbol: 'Cd', number: 48, weight: 112.41, type: 'metal' },
        { name: '铟', symbol: 'In', number: 49, weight: 114.82, type: 'metal' },
        { name: '锡', symbol: 'Sn', number: 50, weight: 118.71, type: 'metal' },
        { name: '锑', symbol: 'Sb', number: 51, weight: 121.76, type: 'metal' },
        { name: '碲', symbol: 'Te', number: 52, weight: 127.6, type: 'nonmetal' },
        { name: '碘', symbol: 'I', number: 53, weight: 126.9, type: 'nonmetal' },
        { name: '氙', symbol: 'Xe', number: 54, weight: 131.29, type: 'noblegas' },
    ],
    [
        { name: '铯', symbol: 'Cs', number: 55, weight: 132.91, type: 'metal' },
        { name: '钡', symbol: 'Ba', number: 56, weight: 137.33, type: 'metal' },
        { name: '镧', symbol: 'La', number: 57, weight: 138.91, type: 'lanthanum' },
        { name: '铪', symbol: 'Hf', number: 72, weight: 178.49, type: 'metal' },
        { name: '钽', symbol: 'Ta', number: 73, weight: 180.95, type: 'metal' },
        { name: '钨', symbol: 'W', number: 74, weight: 183.84, type: 'metal' },
        { name: '铼', symbol: 'Re', number: 75, weight: 186.21, type: 'metal' },
        { name: '锇', symbol: 'Os', number: 76, weight: 190.23, type: 'metal' },
        { name: '铱', symbol: 'Ir', number: 77, weight: 192.22, type: 'metal' },
        { name: '铂', symbol: 'Pt', number: 78, weight: 195.09, type: 'metal' },
        { name: '金', symbol: 'Au', number: 79, weight: 196.97, type: 'metal' },
        { name: '汞', symbol: 'Hg', number: 80, weight: 200.59, type: 'metal' },
        { name: '铊', symbol: 'Tl', number: 81, weight: 204.38, type: 'metal' },
        { name: '铅', symbol: 'Pb', number: 82, weight: 207.2, type: 'metal' },
        { name: '铋', symbol: 'Bi', number: 83, weight: 208.98, type: 'metal' },
        { name: '钋', symbol: 'Po', number: 84, weight: 209, type: 'metal' },
        { name: '砹', symbol: 'At', number: 85, weight: 210, type: 'nonmetal' },
        { name: '氡', symbol: 'Rn', number: 86, weight: 222, type: 'noblegas' },
    ],
    [
        { name: '钫', symbol: 'Fr', number: 87, weight: 223, type: 'metal' },
        { name: '镭', symbol: 'Ra', number: 88, weight: 226, type: 'metal' },
        { name: '锕', symbol: 'Ac', number: 89, weight: 227, type: 'actinium' },
        { name: '卢', symbol: 'Rf', number: 104, weight: 267, type: 'metal' },
        { name: ' Dubna', symbol: 'Db', number: 105, weight: 268, type: 'metal' },
        { name: '𬭳', symbol: 'Sg', number: 106, weight: 271, type: 'metal' },
        { name: '玻', symbol: 'Bh', number: 107, weight: 272, type: 'metal' },
        { name: '𬭶', symbol: 'Hs', number: 108, weight: 277, type: 'metal' },
        { name: '麦', symbol: 'Mt', number: 109, weight: 278, type: 'metal' },
        { name: ' Darmstadt', symbol: 'Ds', number: 110, weight: 281, type: 'metal' },
        { name: '伦', symbol: 'Rg', number: 111, weight: 280, type: 'metal' },
        { name: '哥', symbol: 'Cn', number: 112, weight: 285, type: 'metal' },
        { name: '鉨', symbol: 'Nh', number: 113, weight: 286, type: 'metal' },
        { name: '𫓯', symbol: 'Fl', number: 114, weight: 289, type: 'metal' },
        { name: '镆', symbol: 'Mc', number: 115, weight: 290, type: 'metal' },
        { name: '鉝', symbol: 'Lv', number: 116, weight: 293, type: 'metal' },
        { name: '田', symbol: 'Ts', number: 117, weight: 294, type: 'metal' },
        { name: ' Oganesson', symbol: 'Og', number: 118, weight: 294, type: 'noblegas' },
    ],
]

const series = [
    [
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
        { name: '铈', symbol: 'Ce', number: 58, weight: 140.12, type: 'lanthanum' },
        { name: '镨', symbol: 'Pr', number: 59, weight: 140.91, type: 'lanthanum' },
        { name: '钕', symbol: 'Nd', number: 60, weight: 144.24, type: 'lanthanum' },
        { name: '钷', symbol: 'Pm', number: 61, weight: 145, type: 'lanthanum' },
        { name: '钐', symbol: 'Sm', number: 62, weight: 150.36, type: 'lanthanum' },
        { name: '铕', symbol: 'Eu', number: 63, weight: 151.96, type: 'lanthanum' },
        { name: '钆', symbol: 'Gd', number: 64, weight: 157.25, type: 'lanthanum' },
        { name: '铽', symbol: 'Tb', number: 65, weight: 158.93, type: 'lanthanum' },
        { name: '镝', symbol: 'Dy', number: 66, weight: 162.5, type: 'lanthanum' },
        { name: '钬', symbol: 'Ho', number: 67, weight: 164.93, type: 'lanthanum' },
        { name: '铒', symbol: 'Er', number: 68, weight: 167.26, type: 'lanthanum' },
        { name: '铥', symbol: 'Tm', number: 69, weight: 168.93, type: 'lanthanum' },
        { name: '镱', symbol: 'Yb', number: 70, weight: 173.04, type: 'lanthanum' },
        { name: '镥', symbol: 'Lu', number: 71, weight: 174.97, type: 'lanthanum' },
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
    ],
    [
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
        { name: '钍', symbol: 'Th', number: 90, weight: 232.04, type: 'actinium' },
        { name: '镤', symbol: 'Pa', number: 91, weight: 231.04, type: 'actinium' },
        { name: '铀', symbol: 'U', number: 92, weight: 238.03, type: 'actinium' },
        { name: '镎', symbol: 'Np', number: 93, weight: 237, type: 'actinium' },
        { name: '钚', symbol: 'Pu', number: 94, weight: 244, type: 'actinium' },
        { name: '镅', symbol: 'Am', number: 95, weight: 243, type: 'actinium' },
        { name: '锔', symbol: 'Cm', number: 96, weight: 247, type: 'actinium' },
        { name: '锫', symbol: 'Bk', number: 97, weight: 247, type: 'actinium' },
        { name: '锎', symbol: 'Cf', number: 98, weight: 251, type: 'actinium' },
        { name: '锿', symbol: 'Es', number: 99, weight: 252, type: 'actinium' },
        { name: '镄', symbol: 'Fm', number: 100, weight: 257, type: 'actinium' },
        { name: '钔', symbol: 'Md', number: 101, weight: 258, type: 'actinium' },
        { name: '锘', symbol: 'No', number: 102, weight: 259, type: 'actinium' },
        { name: '铹', symbol: 'Lr', number: 103, weight: 262, type: 'actinium' },
        { name: '', symbol: '', number: -1, weight: 0, type: 'empty' },
    ],
];

const niceTypes = {
    'metal': "金属",
    'nonmetal': "非金属",
    'noblegas': "稀有气体",
    'lanthanum': "镧系元素",
    'actinium': "锕系元素"
}
