# 此文件用于导入 `hyprland` 和 `custom` 文件夹中的其他配置文件
# 你应该将你的自定义配置添加到 `custom` 文件夹中的文件里

$qsConfig = ii
exec = hyprctl dispatch submap global # 请勿删除此行，否则将无法使用任何快捷键
submap = global # 这是让 catchall 生效所必需的

# 默认配置
source=~/.config/hypr/hyprland/env.conf
source=~/.config/hypr/hyprland/execs.conf
source=~/.config/hypr/hyprland/general.conf
source=~/.config/hypr/hyprland/rules.conf
source=~/.config/hypr/hyprland/colors.conf
source=~/.config/hypr/hyprland/keybinds.conf

# 自定义配置
source=~/.config/hypr/custom/env.conf
source=~/.config/hypr/custom/execs.conf
source=~/.config/hypr/custom/general.conf
source=~/.config/hypr/custom/rules.conf
source=~/.config/hypr/custom/keybinds.conf
