# 状态栏、壁纸
exec-once = ~/.config/hypr/hyprland/scripts/start_geoclue_agent.sh
exec-once = qs -c $qsConfig &

# 输入法
exec-once = fcitx5

# 核心组件 (认证、锁屏、通知守护进程)
#exec-once = gnome-keyring-daemon --start --components=secrets
# 启动 KWallet
exec-once = /usr/lib/pam_kwallet_init
exec-once = /usr/lib/polkit-kde-authentication-agent-1 || /usr/libexec/polkit-kde-authentication-agent-1  || /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 || /usr/libexec/polkit-gnome-authentication-agent-1
exec-once = hypridle
exec-once = dbus-update-activation-environment --all
exec-once = sleep 1 && dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP # 不知道是什么的修复
exec-once = hyprpm reload

# 音频
exec-once = easyeffects --gapplication-service

# 剪贴板: 历史
# exec-once = wl-paste --watch cliphist store &
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# 光标
exec-once = hyprctl setcursor Bibata-Modern-Classic 24