name: Test Niri Configuration

on:
  push:
    paths:
      - '.config/niri/**'
  pull_request:
    paths:
      - '.config/niri/**'

jobs:
  validate-niri-config:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install Rust and Cargo
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        
    - name: Build niri from source
      run: |
        git clone https://github.com/YaLTeR/niri /tmp/niri
        cd /tmp/niri
        cargo build --release
        sudo install target/release/niri /usr/local/bin/
        
    - name: Validate niri configuration syntax
      run: |
        niri validate .config/niri/config.kdl
        
    - name: Check for required dependencies
      run: |
        echo "Checking for required tools..."
        # Core dependencies (informational - not all available in CI)
        command -v fuzzel >/dev/null 2>&1 || echo "fuzzel not found (expected in CI)"
        command -v grim >/dev/null 2>&1 || echo "grim not found (expected in CI)"
        command -v slurp >/dev/null 2>&1 || echo "slurp not found (expected in CI)"
        command -v wl-copy >/dev/null 2>&1 || echo "wl-copy not found (expected in CI)"
        command -v playerctl >/dev/null 2>&1 || echo "playerctl not found (expected in CI)"
        echo "Dependency check completed (some tools expected to be missing in CI)"
        
    - name: Verify script permissions
      run: |
        test -x .config/niri/start-niri.sh
        test -x .config/niri/niri/scripts/display-config.sh
        echo "Script permissions verified"
        
    - name: Check configuration structure
      run: |
        # Verify main config files exist
        test -f .config/niri/config.kdl
        test -f .config/niri/niri/env.kdl
        test -f .config/niri/niri/execs.kdl
        test -f .config/niri/niri/general.kdl
        test -f .config/niri/niri/rules.kdl
        test -f .config/niri/niri/colors.kdl
        test -f .config/niri/niri/keybinds.kdl
        
        # Verify custom config files exist
        test -f .config/niri/custom/env.kdl
        test -f .config/niri/custom/execs.kdl
        test -f .config/niri/custom/general.kdl
        test -f .config/niri/custom/rules.kdl
        test -f .config/niri/custom/keybinds.kdl
        test -f .config/niri/custom/devices.kdl
        test -f .config/niri/custom/monitors.kdl
        test -f .config/niri/custom/mouse.kdl
        
        echo "Configuration structure verified"